-- Casteel Chapter 2, pp. 51-55
-- Basic SQL SELECT Statements

-- 1. Display a list of all data contained in the BOOKS table.

-- Use wildcard * / ALL
SELECT *
FROM BOOKS;

-- 3. List the title and publication date for each book in the BOOKS table. Use the column
-- heading “Publication Date” for the Pubdate field.

-- Use AS to assign a new alias
SELECT TITLE, PUBDATE AS "Publication Date"
FROM BOOKS;

-- 5. Create a list containing the publisher’s name, the person usually contacted, and the
-- publisher’s telephone number. Rename the contact column “Contact Person” in the displayed
-- results. (Hint: Use the PUBLISHER table.)

SELECT NAME, CONTACT AS "Contact Person", PHONE
FROM PUBLISHER;

-- 7. List the customer number from the ORDERS table for each customer who has placed an
-- order with the bookstore. List each customer number only once.

-- Use DISTINCT to get distinct CUSTOMER# records
-- No need to have a WHERE clause to exclude null records of ORDER# since ORDER# is already a PK, hence non-null

SELECT DISTINCT CUSTOMER#
FROM ORDERS;

-- 9. Create a list of authors that displays the last name followed by the first name for each author.
-- The last names and first names should be separated by a comma and a blank space.

-- Use || to concatenate strings
-- Remember " " are only used for aliases
-- Also, you can't have single quotations ' within a single quotation quote ' ' '
-- Need to use a delimiter q'<something's>'

SELECT LNAME || ' ' || FNAME AS "Author Name"
FROM AUTHOR;

-- 10. List all information for each order item. Include an item total, which can be calculated by
-- multiplying the Quantity and Paideach columns. Use a column alias for the calculated value
-- to show the heading “Item Total” in the output.

-- Using subqueries (SELECT in SELECT)
-- Otherwise you'd have to expand * into ORDER#, ITEM#, ISBN, QUANTITY, PAIDEACH ...

SELECT * FROM ORDERITEMS, (SELECT QUANTITY * PAIDEACH AS "Item Total" FROM ORDERITEMS);

-- The management of JustLee Books has submitted two requests. The first is for a mailing list of
-- all customers stored in the CUSTOMERS table. The second is for a list of the percentage of
-- profit generated by each book in the BOOKS table. The requests are as follows:

-- 1. Create a mailing list from the CUSTOMERS table. The mailing list should display the name,
-- address, city, state, and zip code for each customer. Each customer’s name should be listed
-- in order of last name followed by first name, separated with a comma, and have the column
-- header “Name.” The city and state should be listed as one column of output, with the values
-- separated by a comma and the column header “Location.”

SELECT LASTNAME || ' ' || FIRSTNAME "Name", ADDRESS, CITY || ', ' || STATE AS "Location", ZIP
FROM CUSTOMERS;

-- 2. To determine the percentage of profit for a particular item, subtract the item’s cost from the
-- retail price to calculate the dollar amount of profit, and then divide the profit by the item’s
-- cost. The solution is then multiplied by 100 to determine the profit percentage for each book.
-- Use a SELECT statement to display each book’s title and percentage of profit. For the
-- column displaying the percentage markup, use “Profit %” as the column heading.

-- Use TO_CHAR to convert int to string 
-- Use ROUND to round percentage to 2 dp.

SELECT TO_CHAR(RETAIL - COST, '$99.99') AS "Total Profit", ROUND((RETAIL - COST) / COST * 100, 2) AS "Percentage of Profit"
FROM BOOKS;



