-- Casteel Chapter 11, pp. 420-425
-- Group Functions

-- 8.4.1 Determine how many books are in the Cooking category.

-- Use COUNT to aggregate number of records

SELECT COUNT(*) "Number of Books"
FROM BOOKS
WHERE UPPER(CATEGORY) IN ('COOKING');

-- 8.4.2 Display the number of books with a retail price of more than $30.00.

SELECT COUNT(*) "Number of Books"
FROM BOOKS
WHERE RETAIL > 30;

-- 8.4.3 Determine the total profit generated by sales to customer 1017. Note: Quantity should
-- be reflected in the total profit calculation.

SELECT TO_CHAR(SUM(OI.QUANTITY * (B.RETAIL - B.COST)), '$999.99') AS "Total Profit"
FROM ORDERITEMS OI
JOIN BOOKS B
ON OI.ISBN = B.ISBN
JOIN ORDERS O
ON O.ORDER# = OI.ORDER#
JOIN CUSTOMERS C
ON C.CUSTOMER# = O.CUSTOMER#
WHERE C.CUSTOMER# = 1017;

-- 8.4.4 Determine the average profit generated by orders in the ORDERS table. Note: The
-- total profit by order must be calculated before finding the average profit.

SELECT AVG(SUM(OI.QUANTITY * (B.RETAIL - B.COST))) AS "Average Profit"
FROM ORDERITEMS OI
JOIN BOOKS B
ON B.ISBN = OI.ISBN
GROUP BY OI.ORDER#;

-- 8.4.5 Determine the average retail price of books by publisher name and category. Include only
-- the categories Children and Computer and the groups with an average retail price greater
-- than $50.

SELECT AVG(B.RETAIL) AS "AVERAGE RETAIL"
FROM BOOKS B
JOIN PUBLISHER P
ON B.PUBID = P.PUBID
WHERE UPPER(B.CATEGORY) IN ('CHILDREN', 'COMPUTER')
GROUP BY P.NAME, B.CATEGORY
HAVING AVG(B.RETAIL) > 50;

-- 8.4.6 List the customers living in Georgia or Florida who have recently placed an order totalling
-- more than $80.

SELECT DISTINCT C.FIRSTNAME, C.LASTNAME, C.CUSTOMER#
FROM CUSTOMERS C
JOIN ORDERS O
ON C.CUSTOMER# = O.CUSTOMER#
JOIN ORDERITEMS OI
ON OI.ORDER# = O.ORDER#
WHERE UPPER(C.STATE) IN ('GA', 'FL')
GROUP BY C.FIRSTNAME, C.LASTNAME, C.CUSTOMER#
HAVING SUM(OI.QUANTITY * OI.PAIDEACH) > 80;

-- JustLee Books has a problem: Book storage space is filling up. As a solution, management is
-- considering limiting the inventory to only those books returning at least a 55% profit. Any book
-- returning less than a 55% profit would be dropped from inventory and not reordered. This plan
-- could, however, have a negative impact on overall sales. Management fears that if JustLee
-- stops carrying the less profitable books, the company might lose repeat business from its
-- customers. As part of management’s decision-making process, it wants to know whether
-- current customers purchase less profitable books frequently. Therefore, management wants to
-- know how many times these less profitable books have been purchased recently.

-- Determine which books generate less than a 55% profit and how many copies of these
-- bookshave been sold. Summarize your findings for management, and include a copy of the
-- query used to retrieve data from the database tables.

SELECT B.TITLE, SUM(OI.QUANTITY) AS "Quantity Sold"
FROM BOOKS B
JOIN ORDERITEMS OI
ON B.ISBN = OI.ISBN
GROUP BY B.TITLE
HAVING SUM(OI.QUANTITY * (B.RETAIL - B.COST))/SUM(OI.QUANTITY * B.COST) * 100 < 55;

SELECT B.TITLE, TO_CHAR(NVL(SUM(OI.QUANTITY), 0), '999') AS "Quantity Sold"
FROM BOOKS B
LEFT OUTER JOIN ORDERITEMS OI
ON B.ISBN = OI.ISBN
GROUP BY B.TITLE
HAVING AVG((NVL(OI.PAIDEACH, 0) - B.COST)/B.COST) * 100 < 55;

