-- Casteel Chapter 10, pp. 377-381
-- Selected Single-Row Functions

-- 1. Produce a list of all customer names in which the first letter of the first and last names is in
-- uppercase and the rest are in lowercase.

-- Use INITCAP to uppercase the first letter and lowercase the rest

SELECT INITCAP(FIRSTNAME), INITCAP(LASTNAME)
FROM CUSTOMERS;

-- 2. Create a list of all customer numbers along with text indicating whether the customer has
-- been referred by another customer. Display the text “NOT REFERRED” if the customer wasn’t
-- referred to JustLee Books by another customer or “REFERRED” if the customer was referred.

-- Use CASE, WHEN, THEN, ELSE, END to specify values based on conditions

SELECT CUSTOMER#, 
    CASE
        WHEN REFERRED IS NOT NULL THEN 'REFERRED'
        ELSE 'NOT REFERRED'
    END AS "REFERRED?"
FROM CUSTOMERS;

-- 3. Determine the amount of total profit generated by the book purchased on order 1002. Display
-- the book title and profit. The profit should be formatted to display a dollar sign and two
-- decimal places. Take into account that the customer might not pay the full retail price, and each
-- item ordered can involve multiple copies.

SELECT B.TITLE, TO_CHAR(O.QUANTITY * O.PAIDEACH - B.COST, '$99.99') AS "Profit"
FROM ORDERITEMS O
JOIN BOOKS B
ON O.ISBN = B.ISBN
WHERE ORDER# = 1002;

-- 8. Using today’s date, determine the age (in months) of each book that JustLee sells. Make sure
-- only whole months are displayed; ignore any portions of months. Display the book title,
-- publication date, current date, and age.

-- Truncate since we want to know only the 'completed' months
-- SYSDATE returns the current system date

SELECT TITLE, PUBDATE, SYSDATE, TRUNC(MONTHS_BETWEEN(SYSDATE, PUBDATE), 0)
FROM BOOKS;

-- 9. Determine the calendar date of the next occurrence of Wednesday, based on today’s date

-- NEXT_DAY gets the closest date for the specified day

SELECT NEXT_DAY(SYSDATE, 'Wednesday')
FROM DUAL;